// <auto-generated />
using System;
using EhpadVaccin.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EhpadVaccin.ORM.Migrations
{
    [DbContext(typeof(Contexte))]
    partial class ContexteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("EhpadVaccin.ORM.Injection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateInjection")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateRappel")
                        .HasColumnType("TEXT");

                    b.Property<string>("marque")
                        .HasColumnType("TEXT");

                    b.Property<int>("numLot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("personneId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("typeVaccinId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("personneId");

                    b.HasIndex("typeVaccinId");

                    b.ToTable("Injections");
                });

            modelBuilder.Entity("EhpadVaccin.ORM.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateNaissace")
                        .HasColumnType("TEXT");

                    b.Property<string>("nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("prenom")
                        .HasColumnType("TEXT");

                    b.Property<int>("role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sexe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("EhpadVaccin.ORM.Vaccin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vaccins");
                });

            modelBuilder.Entity("EhpadVaccin.ORM.Injection", b =>
                {
                    b.HasOne("EhpadVaccin.ORM.Personne", "personne")
                        .WithMany()
                        .HasForeignKey("personneId");

                    b.HasOne("EhpadVaccin.ORM.Vaccin", "typeVaccin")
                        .WithMany()
                        .HasForeignKey("typeVaccinId");

                    b.Navigation("personne");

                    b.Navigation("typeVaccin");
                });
#pragma warning restore 612, 618
        }
    }
}
